events {}
http {
    include /etc/nginx/mime.types;
    
    # Logging to stdout/stderr for container logs
    access_log /dev/stdout;
    error_log /dev/stderr;

    server {
        listen 8080;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;
        # Do not cache index.html so the browser always loads the latest Angular JS bundles
        location /index.html {
            add_header Cache-Control "no-store, no-cache, must-revalidate";
            try_files $uri =404;
        }

        location / {
            try_files $uri $uri/ /index.html;
            # Cache static assets (JS, CSS, images) aggressively
            expires 1y;
            add_header Cache-Control "public";
        }
    }
}